# Generated by Django 5.2.1 on 2025-10-06 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên phòng ban')),
                ('department_type', models.CharField(choices=[('hanh_chinh', 'Hành chính - Tổng hợp'), ('tai_chinh', 'Tài chính - Kế toán'), ('tu_phap', 'Tư pháp - Hộ tịch'), ('xay_dung', 'Xây dựng - Đô thị'), ('kinh_te', 'Kinh tế'), ('van_hoa', 'Văn hóa - Xã hội'), ('dan_so', 'Dân số - KHHGĐ'), ('lao_dong', 'Lao động - Thương binh'), ('cong_an', 'Công an'), ('y_te', 'Y tế'), ('giao_duc', 'Giáo dục'), ('khac', 'Khác')], default='hanh_chinh', max_length=50, verbose_name='Loại phòng ban')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('address', models.CharField(max_length=300, verbose_name='Địa chỉ')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('hotline', models.CharField(blank=True, max_length=20, verbose_name='Đường dây nóng')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='Fax')),
                ('working_hours', models.CharField(default='Thứ 2 - Thứ 6: 7h30 - 11h30, 13h30 - 17h30', max_length=200, verbose_name='Giờ làm việc')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('map_embed', models.TextField(blank=True, verbose_name='Google Maps Embed Code')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Phòng ban',
                'verbose_name_plural': 'Các phòng ban',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên đường dây')),
                ('emergency_type', models.CharField(choices=[('canh_sat', 'Công an/Cảnh sát'), ('cuu_hoa', 'Cứu hỏa'), ('y_te', 'Y tế cấp cứu'), ('dien_nuoc', 'Điện nước'), ('hanh_chinh', 'Hành chính khẩn cấp'), ('khac', 'Khác')], max_length=50, verbose_name='Loại')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
            ],
            options={
                'verbose_name': 'Đường dây khẩn cấp',
                'verbose_name_plural': 'Các đường dây khẩn cấp',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('position', models.CharField(choices=[('truong_phong', 'Trưởng phòng'), ('pho_phong', 'Phó phòng'), ('chuyen_vien', 'Chuyên viên'), ('nhan_vien', 'Nhân viên'), ('khac', 'Khác')], max_length=50, verbose_name='Chức vụ')),
                ('position_custom', models.CharField(blank=True, max_length=100, verbose_name='Chức vụ khác (nếu có)')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Di động')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('display_order', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contacts.department', verbose_name='Phòng ban')),
            ],
            options={
                'verbose_name': 'Người liên hệ',
                'verbose_name_plural': 'Danh sách người liên hệ',
                'ordering': ['display_order', 'full_name'],
            },
        ),
    ]
