# Generated by Django 5.2.1 on 2025-10-02 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('priority_level', models.IntegerField(choices=[(1, 'Thấp'), (2, 'Trung bình'), (3, 'Cao'), (4, 'Khẩn cấp')], default=1, verbose_name='Mức độ ưu tiên')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['-priority_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('name', models.CharField(blank=True, default='Ẩn danh', max_length=200, verbose_name='Tên người phản ánh')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='Ẩn danh')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email (tùy chọn)')),
                ('priority', models.IntegerField(choices=[(1, 'Thấp'), (2, 'Trung bình'), (3, 'Cao'), (4, 'Khẩn cấp')], default=2, verbose_name='Mức độ ưu tiên')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung phản ánh')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ xử lý'), ('processing', 'Đang xử lý'), ('resolved', 'Đã giải quyết'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Địa chỉ')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Vĩ độ')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kinh độ')),
                ('admin_note', models.TextField(blank=True, verbose_name='Ghi chú của admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Ngày giải quyết')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Phản ánh',
                'verbose_name_plural': 'Phản ánh',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feedback_images/%Y/%m/%d/', verbose_name='Hình ảnh')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Chú thích')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tải lên')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='feedback.feedback', verbose_name='Phản ánh')),
            ],
            options={
                'verbose_name': 'Hình ảnh',
                'verbose_name_plural': 'Hình ảnh',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['-created_at'], name='feedback_fe_created_a1f280_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['tracking_code'], name='feedback_fe_trackin_c4b222_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['status'], name='feedback_fe_status_35d074_idx'),
        ),
    ]
