# Generated by Django 5.2.1 on 2025-10-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ví dụ: Cấp lại Giấy phép lái xe', max_length=255, verbose_name='Tên Thủ tục Hành chính')),
                ('public_sector', models.CharField(help_text='Ví dụ: Giao thông Vận tải, Tư pháp', max_length=100, verbose_name='Lĩnh vực')),
                ('department', models.CharField(help_text='Ví dụ: Cục Cảnh sát Giao thông, Sở Tư pháp', max_length=150, verbose_name='Cơ quan Thực hiện')),
                ('jurisdiction', models.CharField(choices=[('cap_tinh', 'Cấp Tỉnh'), ('cap_huyen', 'Cấp Huyện'), ('cap_xa', 'Cấp Xã'), ('trung_uong', 'Trung ương')], default='cap_tinh', max_length=50, verbose_name='Phạm vi Thực hiện')),
                ('service_level', models.IntegerField(choices=[(1, 'Mức 1 - Thông tin'), (2, 'Mức 2 - Tương tác một chiều'), (3, 'Mức 3 - Tương tác hai chiều'), (4, 'Mức 4 - Giao dịch điện tử')], default=4, verbose_name='Mức độ Dịch vụ Công')),
                ('description', models.TextField(blank=True, help_text='Mô tả tóm tắt hoặc chi tiết về thủ tục', verbose_name='Mô tả')),
                ('legal_basis', models.TextField(blank=True, help_text='Các văn bản luật, nghị định', verbose_name='Căn cứ Pháp lý')),
                ('procedure_steps', models.TextField(blank=True, help_text='Các bước thực hiện thủ tục (mỗi bước một dòng)', verbose_name='Trình tự Thực hiện')),
                ('processing_time', models.CharField(blank=True, help_text='Ví dụ: 05 ngày làm việc', max_length=50, verbose_name='Thời hạn Giải quyết')),
                ('fee', models.CharField(blank=True, help_text='Ví dụ: 135.000 VNĐ hoặc Miễn phí', max_length=100, verbose_name='Phí và Lệ phí')),
                ('required_documents', models.TextField(blank=True, help_text='Các giấy tờ cần nộp (mỗi loại một dòng)', verbose_name='Thành phần Hồ sơ')),
                ('contact_info', models.CharField(blank=True, help_text='Cơ quan hỗ trợ, địa chỉ, số điện thoại, email', max_length=255, verbose_name='Thông tin Liên hệ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Dịch vụ Hành chính Công',
                'verbose_name_plural': 'Dịch vụ Hành chính Công',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
